DELETE http://localhost:3001/api/persons/790841449

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Mia", 
    "number": "109232434"
}

###
GET http://localhost:3001/api/persons